// Re-export everything from localData so all imports still work
// When the backend is running, you can swap this to use axios HTTP calls instead
export {
  getAllSlots,
  getSlot,
  getSlotById,
  createNewGame,
  deleteSlot,
  updatePlayerName,
  updateProfileImage,
  updatePlaytime,
  equipItem,
  setCharm,
  getAllShopItems,
  getShopItemsByCategory,
  purchaseItem,
  getPlayerItems,
  getPlayerItemsByCategory,
  getEnemyForRoom,
  processBattleVictory,
  usePotion,
  getUpgradeInfo,
  performUpgrade,
  performTrade,
  devLogin,
  getAllEnemies,
  updateEnemy,
  createEnemy,
  deleteEnemy,
  getAllShopItemsAdmin,
  updateShopItem,
  createShopItem,
  deleteShopItem,
  getAllConfigs,
  updateConfig,
  getAllRewards,
  updateReward,
} from './localData';
