
spring.datasource.url=jdbc:mysql://localhost:3306/momo_regular_expedition
spring.datasource.username=root
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

app.cors.allowed-origins=http://localhost:5173

# File upload (for player profile images)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

